# -*- coding: utf-8 -*-
"""patches.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AuL7jEVM3xLm32AUQaCpi7LmKtFAdii-
"""

# patches.py
import torch

def patch_torch_classes():
    if not hasattr(torch.classes, '__path__'):
        class DummyPath:
            _path = []
        torch.classes.__path__ = DummyPath()